services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: python314_dev_container
    ports:
      - "8000:8000"
    volumes:
      # Spiegelt den lokalen Code in den Container (für Hot-Reloading)
      - .:/app
      # Verhindert, dass der lokale __pycache__ in den Container überschreibt
      - /app/__pycache__
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
